<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wiki</string>
		<string>confluence</string>
		<string>cwf</string>
	</array>
	<key>name</key>
	<string>Confluence Wiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#character-escape</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#code-blocks</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#page-link</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block-macro</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lists</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#text-styling</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline-macro</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>anchor-macro</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.macro.name.confluence entity.name.tag.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.macro.settings.confluence meta.macro.settings.key.confluence constant.other.confluence</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;!\\)({)(anchor)(:)([^}]+?)(})</string>
			<key>name</key>
			<string>meta.macro.anchor.confluence</string>
		</dict>
		<key>block-macro</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#headings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#horizontal-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#table-header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#table-cell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#info-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#note-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tip-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#warning-macro</string>
				</dict>
			</array>
		</dict>
		<key>block-quote</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.quote.confluence</string>
			<key>match</key>
			<string>((?:^|\s+)bq\.)</string>
			<key>name</key>
			<string>markup.quote.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#page-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
			</array>
		</dict>
		<key>bold</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\w)(?&lt;!\\)\*(?=.+?(?&lt;!\\)\*)</string>
			<key>end</key>
			<string>(?&lt;!\\)\*(?!\w)</string>
			<key>name</key>
			<string>meta.bold.confluence markup.bold.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>character-escape</key>
		<dict>
			<key>match</key>
			<string>(\\(\||{|}|\[|\]|\(|\)|\*|_|-|\+|\\|\?|~|\^))</string>
			<key>name</key>
			<string>meta.character-escape.confluence constant.character.escape.confluence</string>
		</dict>
		<key>citation</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\w)(?&lt;!\\)\?\?(?=.+?(?&lt;!\\)\?\?)</string>
			<key>end</key>
			<string>(?&lt;!\\)\?\?(?!\w)</string>
			<key>name</key>
			<string>meta.citation.confluence markup.italic.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>code-block-cs</key>
		<dict>
			<key>begin</key>
			<string>(?={code:language=(csharp|c#))</string>
			<key>end</key>
			<string>(?&lt;={code})</string>
			<key>name</key>
			<string>meta.code.cs.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!{code})</string>
					<key>end</key>
					<string>({)(code)(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.macro.name.confluence entity.name.tag.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.cs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code-block-html</key>
		<dict>
			<key>begin</key>
			<string>(?={code:language=html)</string>
			<key>end</key>
			<string>(?&lt;={code})</string>
			<key>name</key>
			<string>meta.code.html.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!{code})</string>
					<key>end</key>
					<string>({)(code)(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.macro.name.confluence entity.name.tag.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code-block-javascript</key>
		<dict>
			<key>begin</key>
			<string>(?={code:language=javascript)</string>
			<key>end</key>
			<string>(?&lt;={code})</string>
			<key>name</key>
			<string>meta.code.javascript.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!{code})</string>
					<key>end</key>
					<string>({)(code)(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.macro.name.confluence entity.name.tag.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code-block-shell</key>
		<dict>
			<key>begin</key>
			<string>(?={code:language=shell)</string>
			<key>end</key>
			<string>(?&lt;={code})</string>
			<key>name</key>
			<string>meta.code.shell.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!{code})</string>
					<key>end</key>
					<string>({)(code)(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.macro.name.confluence entity.name.tag.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code-block-sql</key>
		<dict>
			<key>begin</key>
			<string>(?={code:language=sql)</string>
			<key>end</key>
			<string>(?&lt;={code})</string>
			<key>name</key>
			<string>meta.code.sql.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!{code})</string>
					<key>end</key>
					<string>({)(code)(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.macro.name.confluence entity.name.tag.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.plsql.oracle</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code-block-xml</key>
		<dict>
			<key>begin</key>
			<string>(?={code:language=xml)</string>
			<key>end</key>
			<string>(?&lt;={code})</string>
			<key>name</key>
			<string>meta.code.xml.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!{code})</string>
					<key>end</key>
					<string>({)(code)(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.macro.name.confluence entity.name.tag.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code-blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#recognized-code-blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unrecognized-code-block</string>
				</dict>
			</array>
		</dict>
		<key>heading-1</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.heading.1.text.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(h1\.) (.*)$</string>
			<key>name</key>
			<string>meta.heading.1.confluence markup.heading.1.confluence</string>
		</dict>
		<key>heading-2</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.heading.2.confluence markup.heading.2.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(h2\.) (.*)$</string>
			<key>name</key>
			<string>meta.heading.2.confluence markup.heading.2.confluence</string>
		</dict>
		<key>heading-3</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.heading.3.confluence markup.heading.3.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(h3\.) (.*)$</string>
			<key>name</key>
			<string>meta.heading.3.confluence markup.heading.3.confluence</string>
		</dict>
		<key>heading-4</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.heading.4.confluence markup.heading.4.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(h4\.) (.*)$</string>
			<key>name</key>
			<string>meta.heading.4.confluence markup.heading.4.confluence</string>
		</dict>
		<key>heading-5</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.heading.5.confluence markup.heading.5.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(h5\.) (.*)$</string>
			<key>name</key>
			<string>meta.heading.5.confluence markup.heading.5.confluence</string>
		</dict>
		<key>heading-6</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.heading.6.confluence markup.heading.6.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(h6\.) (.*)$</string>
			<key>name</key>
			<string>meta.heading.6.confluence markup.heading.6.confluence</string>
		</dict>
		<key>headings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#heading-1</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading-2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading-3</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading-4</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading-5</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading-6</string>
				</dict>
			</array>
		</dict>
		<key>horizontal-line</key>
		<dict>
			<key>match</key>
			<string>(^\s*----\s*$)</string>
			<key>name</key>
			<string>meta.separator.horizontal.confluence markup.separator.horizontal.confluence</string>
		</dict>
		<key>image-link</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.link.destination.image.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;!\w)(?&lt;!\\)!([^!]+?)!(?!\w)</string>
			<key>name</key>
			<string>markup.underline.link.image.confluence</string>
		</dict>
		<key>info-macro</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)({)(info)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.macro.name entity.name.tag.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>({)(info)(})</string>
			<key>name</key>
			<string>meta.macro.info.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#recognized-macro-setting-helper</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
			</array>
		</dict>
		<key>inline-macro</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#character-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#page-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#anchor-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
			</array>
		</dict>
		<key>italic</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\w)(?&lt;!\\)_(?=.+?(?&lt;!\\)_)</string>
			<key>end</key>
			<string>(?&lt;!\\)_(?!\w)</string>
			<key>name</key>
			<string>meta.italic.confluence markup.italic.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>lists</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ordered-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#simple-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unordered-list</string>
				</dict>
			</array>
		</dict>
		<key>macro-key-value-pair</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.macro.settings.confluence meta.macro.settings.key.confluence constant.other.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.macro.settings.confluence meta.operator.confluence keyword.operator.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.macro.settings.confluence meta.macro.settings.value.confluence string.unquoted.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([^=|}]+?)(?:(=)((?:[^|}]+)))?</string>
		</dict>
		<key>macro-settings</key>
		<dict>
			<key>name</key>
			<string>meta.macro.settings.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:|\|)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-key-value-pair</string>
				</dict>
			</array>
		</dict>
		<key>note-macro</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)({)(note)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.macro.name entity.name.tag.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>({)(note)(})</string>
			<key>name</key>
			<string>meta.macro.note.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#recognized-macro-setting-helper</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
			</array>
		</dict>
		<key>ordered-list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.list.confluence meta.list.numbered.confluence markup.list.numbered.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((?:^|(?&lt;=\|)\s+)(?:\#(?:\*|\#)*) )</string>
			<key>name</key>
			<string>meta.list.confluence meta.list.numbered.confluence markup.list.numbered.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>page-link</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.link.title.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.link.destination.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;!\\)\[([^|]*?)(?:\|([^]]*))?\]</string>
			<key>name</key>
			<string>markup.underline.link.confluence</string>
		</dict>
		<key>preformatted</key>
		<dict>
			<key>begin</key>
			<string>({{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.operator.subtle.confluence keyword.operator.subtle.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(}})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.operator.subtle.confluence keyword.operator.subtle.confluence</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.preformatted.confluence markup.code.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#character-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#page-link</string>
				</dict>
			</array>
		</dict>
		<key>recognized-code-blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code-block-cs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-block-html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-block-javascript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-block-shell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-block-sql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-block-xml</string>
				</dict>
			</array>
		</dict>
		<key>recognized-macro-setting-helper</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.macro.settings.key.confluence constant.other.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>meta.macro.settings.value.confluence string.unquoted.confluence</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>meta.macro.settings.key.confluence constant.other.confluence</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>meta.macro.settings.value.confluence string.unquoted.confluence</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:(:)(?:([^=|}]+?)(=)([^=|}]+?)(\|))*([^=|}]+?)(=)([^}]+?))?(})</string>
					<key>name</key>
					<string>meta.macro.settings.confluence</string>
				</dict>
			</array>
		</dict>
		<key>secondary-table-cell</key>
		<dict>
			<key>begin</key>
			<string>(?:\s+(\|))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.table.cell.subtle.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\||$)</string>
			<key>name</key>
			<string>meta.table.cell.confluence markup.table.cell.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#secondary-table-header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#secondary-table-cell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#page-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
			</array>
		</dict>
		<key>secondary-table-header</key>
		<dict>
			<key>begin</key>
			<string>(?:\s+(\|\|))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.table.header.subtle.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\||$)</string>
			<key>name</key>
			<string>meta.table.header.confluence markup.table.header.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#secondary-table-header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#secondary-table-cell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#page-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
			</array>
		</dict>
		<key>simple-list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.list.confluence meta.list.unnumbered.simple.confluence markup.list.unnumbered.simple.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^(?:-)|(?:(?&lt;=\|)\s+(?:-)) )</string>
			<key>name</key>
			<string>meta.list.confluence meta.list.unnumbered.simple.confluence markup.list.unnumbered.simple.confluence</string>
		</dict>
		<key>single-macro</key>
		<dict>
			<key>begin</key>
			<string>({)([^}:]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.macro.name.confluence entity.name.tag.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.macro</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macro-settings</string>
				</dict>
			</array>
		</dict>
		<key>strikethrough</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!(?:\\|\w))-(?=.+?(?&lt;!\\)-)</string>
			<key>end</key>
			<string>((?&lt;!\\)-)(?!\w)</string>
			<key>name</key>
			<string>meta.strikethrough.confluence markup.underline.strikethrough.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>subscript</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)~(?=.+?(?&lt;!\\)~)</string>
			<key>end</key>
			<string>(?&lt;!\\)~(?!\w)</string>
			<key>name</key>
			<string>meta.subscript.confluence markup.other.subscript.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>superscript</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)\^(?=.+?(?&lt;!\\)\^)</string>
			<key>end</key>
			<string>(?&lt;!\\)\^(?!\w)</string>
			<key>name</key>
			<string>meta.superscript.confluence markup.other.superscript.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>table-cell</key>
		<dict>
			<key>begin</key>
			<string>^((?:\s*\|))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.table.cell.subtle.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.table.cell.confluence markup.table.cell.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#secondary-table-header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#secondary-table-cell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#page-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
			</array>
		</dict>
		<key>table-header</key>
		<dict>
			<key>begin</key>
			<string>^((?:\s*\|\|))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.table.header.subtle.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.table.header.confluence markup.table.header.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#secondary-table-header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#secondary-table-cell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#page-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
			</array>
		</dict>
		<key>text-styling</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#character-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preformatted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#underline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strikethrough</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#citation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subscript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#superscript</string>
				</dict>
			</array>
		</dict>
		<key>tip-macro</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)({)(tip)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.macro.name entity.name.tag.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>({)(tip)(})</string>
			<key>name</key>
			<string>meta.macro.tip.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#recognized-macro-setting-helper</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
			</array>
		</dict>
		<key>underline</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\w)(?&lt;!\\)\+(?=.+?(?&lt;!\\)\+)</string>
			<key>end</key>
			<string>(?&lt;!\\)\+(?!\w)</string>
			<key>name</key>
			<string>meta.underline.confluence markup.underline.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>unordered-list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.list.confluence meta.list.unnumbered.confluence markup.list.unnumbered.confluence</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((?:^|(?&lt;=\|)\s+)(?:\*(?:\*|\#)*) )</string>
			<key>name</key>
			<string>meta.list.confluence meta.list.unnumbered.confluence markup.list.unnumbered.confluence</string>
		</dict>
		<key>unrecognized-code-block</key>
		<dict>
			<key>begin</key>
			<string>(?={code)</string>
			<key>end</key>
			<string>(?&lt;={code})</string>
			<key>name</key>
			<string>meta.code.raw.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!{code})</string>
					<key>contentName</key>
					<string>meta.code.raw.confluence markup.raw</string>
					<key>end</key>
					<string>({)(code)(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.macro.name.confluence entity.name.tag.confluence</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.operator.confluence keyword.operator.confluence</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>warning-macro</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)({)(warning)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.macro.name.confluence entity.name.tag.confluence</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.operator.confluence keyword.operator.confluence</string>
				</dict>
			</dict>
			<key>end</key>
			<string>({)(warning)(})</string>
			<key>name</key>
			<string>meta.macro.warning.confluence</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#recognized-macro-setting-helper</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code-blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.wiki.confluence</string>
	<key>uuid</key>
	<string>de43e6f7-a820-4d64-a472-30c79f83a963</string>
</dict>
</plist>
