<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wiki</string>
		<string>confluence</string>
		<string>cwf</string>
	</array>
	<key>name</key>
	<string>Confluence Wiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#character-escape</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lists</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#text-styling</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block-macro</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline-macro</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-macro</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#heading</string>
				</dict>
			</array>
		</dict>
		<key>bold</key>
		<dict>
			<key>begin</key>
			<string>(?:\b|}?)(?&lt;!\\)\*(?=.*?(?&lt;!\\)\*)</string>
			<key>end</key>
			<string>(?&lt;!\\)\*</string>
			<key>name</key>
			<string>markup.bold meta.wiki.bold</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>character-escape</key>
		<dict>
			<key>match</key>
			<string>(\\(\||{|}|\[|\]|\(|\)|\*|_|-|\+))</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>heading</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.heading</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(h[1-6]\.) (.*)$</string>
			<key>name</key>
			<string>markup.heading</string>
		</dict>
		<key>inline-macro</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#character-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#page-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
			</array>
		</dict>
		<key>italic</key>
		<dict>
			<key>begin</key>
			<string>(?:\b|})_(?=.*?_)</string>
			<key>end</key>
			<string>_</string>
			<key>name</key>
			<string>markup.italic meta.wiki.italic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>lists</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ordered-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#simple-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unordered-list</string>
				</dict>
			</array>
		</dict>
		<key>macro-key-value-pair</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.macro.setting meta.macro.key constant.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.macro.setting meta.macro.value string.unquoted</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([^=|}]+?)(?:(=)((?:[^|}]+)))?</string>
		</dict>
		<key>macro-settings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:|\|)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-key-value-pair</string>
				</dict>
			</array>
		</dict>
		<key>ordered-list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.list.numbered</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((?:^|(?&lt;=\|)\s+)(?:\#(?:\*|\#)*) )</string>
			<key>name</key>
			<string>meta.wiki.list</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>page-link</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.wiki.link.title</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.wiki.link.destination</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;!\\)\[([^|]*?)(?:\|([^]]*))?\]</string>
			<key>name</key>
			<string>markup.underline.link</string>
		</dict>
		<key>preformatted</key>
		<dict>
			<key>begin</key>
			<string>({{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.subtle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(}})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.subtle</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.code</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#character-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#page-link</string>
				</dict>
			</array>
		</dict>
		<key>simple-list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.list.unnumbered.simple</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^(?:-)|(?:(?&lt;=\|)\s+(?:-)) )</string>
			<key>name</key>
			<string>meta.wiki.list</string>
		</dict>
		<key>single-macro</key>
		<dict>
			<key>begin</key>
			<string>({)([^}:]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.macro.name entity.name.tag</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.macro</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macro-settings</string>
				</dict>
			</array>
		</dict>
		<key>text-styling</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#character-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preformatted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#underline</string>
				</dict>
			</array>
		</dict>
		<key>underline</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)\+(?=.*(?&lt;!\\)\+)</string>
			<key>end</key>
			<string>(?&lt;!\\)\+</string>
			<key>name</key>
			<string>markup.underline meta.wiki.underline</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#text-styling</string>
				</dict>
			</array>
		</dict>
		<key>unordered-list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.list.unnumbered</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((?:^|(?&lt;=\|)\s+)(?:\*(?:\*|\#)*) )</string>
			<key>name</key>
			<string>meta.wiki.list</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.wiki.confluence</string>
	<key>uuid</key>
	<string>de43e6f7-a820-4d64-a472-30c79f83a963</string>
</dict>
</plist>
