<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wiki</string>
		<string>confluence</string>
		<string>cwf</string>
	</array>
	<key>name</key>
	<string>Confluence Wiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#character-escape</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:({)(code)(?=:language=(?i:sql)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;={code})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#name-value</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>end</key>
					<string>({)(code)(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.script</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.plsql.oracle</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:({)(code)(?=:language=(?i:cs|c#)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;={code})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#name-value</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>end</key>
					<string>({)(code)(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.script</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.cs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#block-level</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single-macro</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-level</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#heading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bullet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
			</array>
		</dict>
		<key>bold</key>
		<dict>
			<key>begin</key>
			<string>(?:\b|}?)(?&lt;!\\)\*(?=.*?(?&lt;!\\)\*)</string>
			<key>end</key>
			<string>(?&lt;!\\)\*</string>
			<key>name</key>
			<string>markup.bold</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>bullet</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((?:\*|-)(?:\*|\#|-)*)</string>
		</dict>
		<key>character-escape</key>
		<dict>
			<key>match</key>
			<string>(\\(\||{|}|\[|\]|\(|\)|\*|_|-|\+))</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>heading</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.heading</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(h[1-6]\.) (.*)$</string>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#character-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#underline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#preformatted</string>
				</dict>
			</array>
		</dict>
		<key>italic</key>
		<dict>
			<key>begin</key>
			<string>(?:\b|})_(?=.*?_)</string>
			<key>end</key>
			<string>_</string>
			<key>name</key>
			<string>markup.italic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\#(?:\*|\#)*)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-level</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>name-value</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.wiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)(?:(=)((?:[^|}]+)))?</string>
		</dict>
		<key>preformatted</key>
		<dict>
			<key>begin</key>
			<string>({{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.subtle variable.parameter</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(}})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.subtle variable.parameter</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.code</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#character-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-macro</string>
				</dict>
			</array>
		</dict>
		<key>single-macro</key>
		<dict>
			<key>begin</key>
			<string>({)([^}:]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#name-value</string>
				</dict>
			</array>
		</dict>
		<key>underline</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)\+(?=.*(?&lt;!\\)\+)</string>
			<key>end</key>
			<string>(?&lt;!\\)\+</string>
			<key>name</key>
			<string>markup.underline</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#character-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.wiki.confluence</string>
	<key>uuid</key>
	<string>de43e6f7-a820-4d64-a472-30c79f83a963</string>
</dict>
</plist>
